### ISSUE TITLE
Couldn't Install cli-purge on MAC OS X

### ISSUE THREAD

**Issue by sudhakaranr87** [akamai/cli-purge#8] opened 2018-10-07 03:52 UTC
Got this below Error,

GLOENML-8ABLFVH:cli-purge urajesu$ go build -o akamai-purge
purge.go:24:2: cannot find package "github.com/akamai/AkamaiOPEN-edgegrid-golang/ccu-v3" in any of:
	/usr/local/go/src/github.com/akamai/AkamaiOPEN-edgegrid-golang/ccu-v3 (from $GOROOT)
	($GOPATH not set)
akamai-purge.go:21:2: cannot find package "github.com/akamai/cli-common-golang" in any of:
	/usr/local/go/src/github.com/akamai/cli-common-golang (from $GOROOT)
	($GOPATH not set)
purge.go:26:2: cannot find package "github.com/fatih/color" in any of:
	/usr/local/go/src/github.com/fatih/color (from $GOROOT)
	($GOPATH not set)
command.go:21:2: cannot find package "github.com/urfave/cli" in any of:
	/usr/local/go/src/github.com/urfave/cli (from $GOROOT)
	($GOPATH not set)
GLOENML-8ABLFVH:cli-purge urajesu$

**Comment by sudhakaranr87** [comment] 2018-10-07 03:57
I have set Environment Variables for GOPATH and GOROOT after then this error,

GLOENML-8ABLFVH:cli-purge urajesu$ go build -o akamai-purge
purge.go:24:2: cannot find package "github.com/akamai/AkamaiOPEN-edgegrid-golang/ccu-v3" in any of:
	/usr/local/go/src/github.com/akamai/AkamaiOPEN-edgegrid-golang/ccu-v3 (from $GOROOT)
	/Users/urajesu/cli-purge/src/github.com/akamai/AkamaiOPEN-edgegrid-golang/ccu-v3 (from $GOPATH)
akamai-purge.go:21:2: cannot find package "github.com/akamai/cli-common-golang" in any of:
	/usr/local/go/src/github.com/akamai/cli-common-golang (from $GOROOT)
	/Users/urajesu/cli-purge/src/github.com/akamai/cli-common-golang (from $GOPATH)
purge.go:26:2: cannot find package "github.com/fatih/color" in any of:
	/usr/local/go/src/github.com/fatih/color (from $GOROOT)
	/Users/urajesu/cli-purge/src/github.com/fatih/color (from $GOPATH)
command.go:21:2: cannot find package "github.com/urfave/cli" in any of:
	/usr/local/go/src/github.com/urfave/cli (from $GOROOT)
	/Users/urajesu/cli-purge/src/github.com/urfave/cli (from $GOPATH)

**Comment by dshafik** [comment] 2018-10-07 04:01
@sudhakaranr87 looking at your errors, your `GOPATH` should be `/usr/local/go` and you should then run `dep ensure` in the root of the repository.

The best option however, is to install using [Akamai CLI](https://developer.akamai.com/cli):

```
$ akamai install purge
```

If it cannot be compiled, it will fetch a binary (it will ask, unless you pass `--force`)

**Comment by sudhakaranr87** [comment] 2018-10-08 03:56
@dshafik : Thanks for the reply! Really Hard to find the Installation steps, Is there any docker images available to use for purging? Also provide me the steps using it.

**Comment by dshafik** [comment] 2018-10-08 06:17
@sudhakaranr87 You can just grab the latest binary from https://github.com/akamai/cli-purge/releases

If those don't meet your needs, let me know!

**Comment by raidenovski** [comment] 2019-01-14 17:38
Hi, I fetched the binaries but cannot purge. It says `Unable to create instance using environment or .edgerc file`. I suppose I should add my credentials somewhere. I tried creating a `.edgerc` file in my home with my email but that didn't work. Any advice? Thanks

**Comment by synedra** [comment] 2019-01-14 17:40
From the Akamai CLI instructions:

Akamai CLI uses the standard Akamai OPEN credentials file, .edgerc. By default, it will look for credentials in your HOME directory.

You can override both the credentials file location, or the section, by passing the the --edgerc or --section flags to each command.

To set up your credential file, see the authorization and credentials sections of the Get Started guide.

**Comment by raidenovski** [comment] 2019-01-15 07:17
Hi, thanks for the response. I have checked the guide and manually created the `.edgerc` file with my generated createntials in this format:

```
[default]
host = akab-xxxxxxxxxxxxxxxx-xxxxxxxxxxxxxxxx.purge.akamaiapis.net
client_token = akab-xxxxxxxxxxxxxxxx-xxxxxxxxxxxxxxxx
client_secret = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
access_token = akab-xxxxxxxxxxxxxxxx-xxxxxxxxxxxxxxxx
```

However, it's still giving the same error.
Even tried to pass the file location, like so:

`akamai purge --edgerc 'Mac/Users/myuser/.edgerc' invalidate 'https://url...'`
and
`akamai purge --edgerc '~r/.edgerc' invalidate 'https://url...'`
but no results.

Reloaded the shell but no results.

**Comment by justinrummel** [comment] 2019-01-15 11:59
Hello @raidenovski try this:

```
akamai purge --edgerc ~/.edgerc --section default invalidate https://www.example.com/
```

**Comment by justinrummel** [comment] 2019-01-15 12:33
Excellent news!  

The issue is each CLI Package (Purge, [Property](https://github.com/akamai/cli-property), [AppSec](https://github.com/akamai/cli-appsec), etc) can assume what is the default label within your .edgerc file.  For purge, it is "ccu" which is described in the help.  Wanted to share that just in case you decide to look at other CLI Packages.

```
ladmin$ akamai purge help | grep -A2 Global
Global Flags:
   --edgerc value   Location of the credentials file (default: "/Users/ladmin/.edgerc") [$AKAMAI_EDGERC]
   --section value  Section of the credentials file (default: "ccu") [$AKAMAI_EDGERC_SECTION]
```

**Comment by dshafik** [comment] 2019-01-15 18:56
Thanks @justinrummel, I'll go ahead and close this.

**Closed by dshafik** 2019-01-15 18:56 UTC

**Comment by dineshpalanivel** [comment] 2021-10-05 05:14
> Hello @raidenovski try this:
> 
> ```
> akamai purge --edgerc ~/.edgerc --section default invalidate https://www.example.com/
> ```

This was super helpful. I would really appreciate if this can be updated in the readme. 
Thank you very much!!
